const enUS = {
  'welcome': 'Welcome to the Note App!',
  'create_note': 'Create a new note',
  'view_all_note': 'View all notes',
  'settings': 'SETTINGS',
  'exit': 'Exit the program',
  'error': 'Error Command Added',
  'new_note_name': 'Add a new note',
  'file_error': "Added note name created earlier! Please try again",
  'write_note': "You can write to Note (click 'save' to save)",
  'save': "SAVE",
  'note_save': "Note saved successfully",
  'number_note': "Enter the Note Number",
  'delete_all': "Delete all Notes",
  'delete_selected': "Selective Delete",
  'no_note': "Notes Available So far",
  'back_to_home': "Return to Main Menu",
  'enter_note_number': "Enter the Note Number",
  'update': "Change",
  'delete': "DELETE",
  'back_to': "go back",
  'edit_note': "Note You can change",
  'previous_note': "Previous Note",
  'succes_delete_all': "All Files Successfully Deleted",
  'select_file': "Select and enter the Files list in the directory",
};