const uzUZ = {
  'welcome': 'Note Appga Xush Kelibsiz!',
  'create_note': 'Yangi noteni yarating',
  'view_all_note': 'Barcha notelarni korish',
  'settings': 'SOZLAMALAR',
  'exit': 'Dasturdan chiqish',
  'error': 'Xato Buyruq Kiritildi',
  'update_note': 'Ozgartirmoqchi bolingan note',
  'new_note_name': 'Yangi Noteni Kiriting',
  'file_error': "Kiritilgan note nomi oldin yaratilgan! Iltimos qaytadan urinib ko'ring",
  'write_note': "Notega Yozishingiz mumkin(Saqlash uchun 'save' sozini bosing)",
  'save': "save",
  'note_save': "Note muvaffaqiyatli saqlandi",
  'number_note': "Note Raqamini Kiriting",
  'delete_all': "Barcha Notelarni o'chirish",
  'delete_selected': "Tanlab O'chirish",
  'no_note': "Hozircha Notelar Mavjud emas",
  'back_to_home': "Bosh Menyuga Qaytish",
  'enter_note_number': "Note Raqamini Kiriting",
  'update': "O'zgartirish",
  'delete': "O'CHIRISH",
  'back_to': "orqaga qaytish",
  'edit_note': "Note O'zgartirishingiz Mumkin",
  'previous_note': "Avvalgi Note",
  'succes_delete_all': "Barcha Fayllar Muvoffaqiyatli O'chirildi",
  'select_file': "Katalogdagi Fayllar ro'yxatini tanlab kiriting",
};